### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by yamash** [montalex/COM-480-Data-Visualization#2]
- [x] Adapt map height when clicked on country
- [x] Add similarities info
- [x] Clean main csv (remove "beer" from description)
- [x] Clean repo
- [x] Beautify website
- [ ] Clean error messages from chart

**Comment by yamash** [comment]
Last TODO:
- [ ] Make demo video 
- [ ] Update readme (change title, add folder desc)
- [ ] Beautify Process Book (if still have time and courage)
